### ISSUE TITLE
Missing PicoTM1637.pio.h and Missing programs

### ISSUE THREAD

**Issue by kiteCTRL** [wahlencraft/TM1637-pico#3]
Hello, I am getting these errors.

fatal error: PicoTM1637.pio.h: No such file or directory
    8 | #include <PicoTM1637.pio.h>

error: 'tm1637_program' undeclared (first use in this function)
   56 |   uint offset = pio_add_program(pio, &tm1637_program);

**Comment by wahlencraft** [comment]
Sounds like a CMake problem. Maybe you missed including the path to the header there? Have you tried running my demo program?
